apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j9hwoq7gj-java-springboot 
  janus-idp.io/tekton: j9hwoq7gj-java-springboot
  backstage.io/kubernetes-id: j9hwoq7gj-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j9hwoq7gj-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml